version: '3.8'
services:
  nextjs-app:
    build: .
    image: emrealgan/pera-marin
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MONGO_URL: ${MONGO_URL}
